name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: ng test --watch=false --code-coverage --browsers=Headless
        
      - name: Test angular action
        uses:  demyanets/angular-coverage-badges-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage-summary-path: coverage/stslib/coverage-summary.json
