name: master

on: [push, pull_request]

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm run test:ci
        
      - name: Test angular action
        uses:  demyanets/angular-coverage-badges-action@v1
        with:
          coverage-summary-path: coverage/stslib/coverage-summary.json
